# https://beta.ruff.rs
name: python
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: # 添加 workflow_dispatch 事件，支持手动触发

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install --user ruff
      - run: ruff check --output-format github --ignore F401 --target-version py38 .
